version: 2

project_name: go-ocproxy

archives:
  - id: macos
    ids:
      - macos-arm64
    formats:
      - tar.gz
    files:
      - none*
  - id: windows
    ids:
      - windows-amd64
    formats:
      - zip
    files:
      - none*
builds:
  - id: macos-arm64
    main: .
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: windows-amd64
    main: .
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"
