version: 2

project_name: go-ocproxy

archives:
  - format: xz
    files:
      - none*
builds:
  - id: goreleaser-multi-arch-docker
    main: ./main.go
    goos:
      - android
      - freebsd
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      # Because they need CGO_ENABLED=1. https://github.com/cli/gh-extension-precompile/issues/50
      - goos: android
        goarch: amd64
      - goos: android
        goarch: 386
      - goos: android
        goarch: arm
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
